import { config } from "dotenv";

config({ path: ".env" });

export const {
  PORT,
  SALT,
  ACCESS_TOKEN_SECRET,
  REFRESH_TOKEN_SECRET,
  CLIENT_URL,
  MAIL_USER,
  MAIL_PASS,
  LOGO_LINK,
  VERIFICATION_CODE_EXPIRY_IN_MINS,
  VERIFICATION_CODE_LENGTH,
  RESET_TOKEN_EXPIRY_IN_MINS,
  RESET_TOKEN_CODE_LENGTH,
  CLOUDINARY_API_KEY,
  CLOUDINARY_CLOUD_NAME,
  CLOUDINARY_API_SECRET,
  MAX_FILE_SIZE,
  NODE_ENV,
} = process.env;
